<?php

namespace App\Tests\Functional\Controller;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class RegistrationControllerTest extends WebTestCase
{

    private $client;
    private $crawler;
    private $form;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->client = static::createClient();
        $this->crawler = $this->client->request('GET', '/register');
        $this->form = $this->crawler->selectButton('Register')->form();
    }

    public function testRegistrationExistence()
    {
        $this->assertResponseIsSuccessful();
    }

    public function testRegistrationFormContents()
    {
        //The first header in registration form is "Register"
        $this->assertSelectorTextContains('h1', 'Register');

        //There should be at least three input fields i.e email, password & confirm-password
        $this->assertEquals(4, $this->crawler->filter('input')->count());
    }

    public function testRegistrationFailsBecauseAllFieldsAreMissing()
    {
        $this->client->submit($this->form);
        $this->assertFalse($this->client->getResponse()->isRedirect('/'));
    }

    public function testNewUserRegistration()
    {
        $this->form['registration_form[email]']->setValue('grv_sh@rediffmail.com');
        $this->form['registration_form[plainPassword][first]']->setValue('mangoDrops');
        $this->form['registration_form[plainPassword][second]']->setValue('mangoDrops');
        $this->client->submit($this->form);
        $this->assertResponseRedirects("/");

        $email = $this->getMailerMessage(0);
        $this->assertEmailHeaderSame($email, 'To', 'grv_sh@rediffmail.com');
    }
}