<?php

namespace App\Tests\Functional\Controller;

use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class SecurityControllerTest extends WebTestCase
{
    private $client;
    private $crawler;
    private $form;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->client = static::createClient();
        $this->crawler = $this->client->request('GET', '/login');
        $this->form = $this->crawler->selectButton('Sign in')->form();
    }

    /**
     * @dataProvider loginCredentials
     * @param $username
     * @param $password
     */
    public function testLogin($username,$password)
    {
        //Test login for at least 2 users with dataProvider option

        $this->form['email']->setValue($username);
        $this->form['password']->setValue($password);
        $this->client->submit($this->form);
        $this->assertResponseRedirects("/dashboard");

        //or
        /*$this->client->request('GET','/dashboard');
        $this->assertResponseIsSuccessful();*/
    }

    public function loginCredentials()
    {
        return [
            ['grv_sh@yahoo.co.in', 'morePizza'],
            ['grv_sh@rediffmail.com','mangoDrops']
        ];
    }

    public function testFastLogin()
    {
        /* Fast login is used in a situation, where logging in user is not first priority
        but implementing functional tests in a protected-page. Fast login can be used to reduce time
        for the time-taking normal login process. */

        $user1 = static::$container->get(UserRepository::class)->findOneByEmail("grv_sh@yahoo.co.in");
        $this->client->loginUser($user1);
        $this->client->request('GET','/dashboard');
        $this->assertResponseIsSuccessful();
    }
}