name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install all dependencies
      run: composer update

    - name: Run all functional tests
      run: ./bin/phpunit tests/Functional/
