name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Run-Tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install all dependencies
        run: composer update

      - name: Functional dashboardControllerTest
        run: sudo phpunit tests/Functional/Controller/DashboardControllerTest.php

      - name: Functional registrationControllerTest
        run: sudo phpunit tests/Functional/Controller/RegistrationControllerTest.php

      - name: Functional securityControllerTest
        run: sudo phpunit tests/Functional/Controller/SecurityControllerTest.php

      - name: Downgrade Google Chrome to 85
        run: |
          wget -q "https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_85.0.4183.121-1_amd64.deb"
          sudo apt-get install --allow-downgrades ./google-chrome-stable_85.0.4183.121-1_amd64.deb

      - name: Panther End2End Test
        run: sudo phpunit tests/Panther/
