name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Run-Tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install all dependencies
        run: composer update

      - name: Functional dashboardControllerTest
        run: sudo phpunit tests/Functional/Controller/DashboardControllerTest.php

      - name: Functional registrationControllerTest
        run: sudo phpunit tests/Functional/Controller/RegistrationControllerTest.php

      - name: Functional securityControllerTest
        run: sudo phpunit tests/Functional/Controller/SecurityControllerTest.php

      - name: Panther End2End Test
        run: sudo PANTHER_CHROME_DRIVER_BINARY=/usr/bin/chromedriver phpunit tests/Panther/
