name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Run-Tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install all dependencies
        run: composer update

      - name: Functional dashboardControllerTest
        run: sudo phpunit tests/Functional/Controller/DashboardControllerTest.php

      - name: Functional registrationControllerTest
        run: sudo phpunit tests/Functional/Controller/RegistrationControllerTest.php

      - name: Functional securityControllerTest
        run: sudo phpunit tests/Functional/Controller/SecurityControllerTest.php

      - name: Installing ChromeDriver and geckodriver
        run: sudo apt-get install chromium-chromedriver firefox-geckodriver

      - name: Panther End2End Test
        env:
          PANTHER_CHROME_DRIVER_BINARY: "/usr/bin/chromedriver"
        run: sudo phpunit tests/Panther/
